// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bound value that can be a literal or a data binding path
 */
export type BoundValue = { literalString: string, } | { literalNumber: number, } | { literalBoolean: boolean, } | { path: string, };
