// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueMap } from "./ValueMap";

export type DataModelUpdatePayload = { surfaceId: string, path: string | null, contents: Array<ValueMap>, };
