// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Component } from "./Component";

export type SurfaceUpdatePayload = { surfaceId: string, components: Array<Component>, };
