// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user action sent from the client
 */
export type UserAction = { name: string, surfaceId: string, sourceComponentId: string, timestamp: string, context: Record<string, unknown>, };
