/**
 * Zod Schema Validation for A2UI Protocol Messages
 *
 * These schemas provide runtime validation for A2UI messages
 * received from the backend via SSE.
 *
 * The schemas mirror the TypeScript types generated by ts-rs from Rust.
 */

import { z } from 'zod';

// ============================================================================
// Value Types
// ============================================================================

/**
 * A bound value that can be a literal or a data binding path
 */
export const BoundValueSchema = z.union([
  z.object({ literalString: z.string() }),
  z.object({ literalNumber: z.number() }),
  z.object({ literalBoolean: z.boolean() }),
  z.object({ path: z.string() }),
]);

export type BoundValue = z.infer<typeof BoundValueSchema>;

// ============================================================================
// Data Model Types
// ============================================================================

/**
 * A value in the data model (recursive structure)
 */
export const ValueMapSchema: z.ZodType<{
  key: string;
  valueString?: string;
  valueNumber?: number;
  valueBoolean?: boolean;
  valueMap?: unknown[];
}> = z.lazy(() =>
  z.object({
    key: z.string(),
    valueString: z.string().optional(),
    valueNumber: z.number().optional(),
    valueBoolean: z.boolean().optional(),
    valueMap: z.array(ValueMapSchema).optional(),
  })
);

export type ValueMap = z.infer<typeof ValueMapSchema>;

// ============================================================================
// Component Types
// ============================================================================

/**
 * A UI component definition
 */
export const ComponentSchema = z.object({
  id: z.string(),
  component: z.record(z.string(), z.unknown()),
});

export type Component = z.infer<typeof ComponentSchema>;

/**
 * Template binding for dynamic children
 */
export const TemplateBindingSchema = z.object({
  componentId: z.string(),
  dataBinding: z.string(),
});

export type TemplateBinding = z.infer<typeof TemplateBindingSchema>;

/**
 * Children definition for container components
 */
export const ChildrenSchema = z.union([
  z.object({ explicitList: z.array(z.string()) }),
  z.object({ template: TemplateBindingSchema }),
]);

export type Children = z.infer<typeof ChildrenSchema>;

// ============================================================================
// Action Types
// ============================================================================

/**
 * Context for an action
 */
export const ActionContextSchema = z.object({
  key: z.string(),
  value: BoundValueSchema,
});

export type ActionContext = z.infer<typeof ActionContextSchema>;

/**
 * An action that can be triggered by user interaction
 */
export const ActionSchema = z.object({
  name: z.string(),
  context: z.array(ActionContextSchema).optional(),
});

export type Action = z.infer<typeof ActionSchema>;

// ============================================================================
// Message Payload Types
// ============================================================================

/**
 * Surface update payload
 */
export const SurfaceUpdatePayloadSchema = z.object({
  surfaceId: z.string(),
  components: z.array(ComponentSchema),
});

export type SurfaceUpdatePayload = z.infer<typeof SurfaceUpdatePayloadSchema>;

/**
 * Data model update payload
 */
export const DataModelUpdatePayloadSchema = z.object({
  surfaceId: z.string(),
  path: z.string().optional(),
  contents: z.array(ValueMapSchema),
});

export type DataModelUpdatePayload = z.infer<typeof DataModelUpdatePayloadSchema>;

/**
 * Begin rendering payload
 */
export const BeginRenderingPayloadSchema = z.object({
  surfaceId: z.string(),
  root: z.string(),
});

export type BeginRenderingPayload = z.infer<typeof BeginRenderingPayloadSchema>;

/**
 * Delete surface payload
 */
export const DeleteSurfacePayloadSchema = z.object({
  surfaceId: z.string(),
});

export type DeleteSurfacePayload = z.infer<typeof DeleteSurfacePayloadSchema>;

// ============================================================================
// A2UI Message Types
// ============================================================================

/**
 * A2UI protocol message (discriminated union)
 */
export const A2UIMessageSchema = z.union([
  z.object({ surfaceUpdate: SurfaceUpdatePayloadSchema }),
  z.object({ dataModelUpdate: DataModelUpdatePayloadSchema }),
  z.object({ beginRendering: BeginRenderingPayloadSchema }),
  z.object({ deleteSurface: DeleteSurfacePayloadSchema }),
]);

export type A2UIMessage = z.infer<typeof A2UIMessageSchema>;

// ============================================================================
// User Action Types
// ============================================================================

/**
 * A user action sent from the client
 */
export const UserActionSchema = z.object({
  name: z.string(),
  surfaceId: z.string(),
  sourceComponentId: z.string(),
  timestamp: z.string(),
  context: z.record(z.string(), z.unknown()),
});

export type UserAction = z.infer<typeof UserActionSchema>;

// ============================================================================
// Validation Utilities
// ============================================================================

export interface ValidationResult<T> {
  success: boolean;
  data?: T;
  error?: z.ZodError;
}

/**
 * Validate an A2UI message with detailed error reporting
 */
export function validateA2UIMessage(data: unknown): ValidationResult<A2UIMessage> {
  const result = A2UIMessageSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}

/**
 * Format Zod error for display
 */
export function formatValidationError(error: z.ZodError): string {
  return error.issues
    .map((issue) => {
      const path = issue.path.length > 0 ? issue.path.join('.') : 'root';
      return `[${path}] ${issue.message}`;
    })
    .join('\n');
}

/**
 * Get message type from A2UI message
 */
export function getMessageType(message: A2UIMessage): string {
  if ('surfaceUpdate' in message) return 'surfaceUpdate';
  if ('dataModelUpdate' in message) return 'dataModelUpdate';
  if ('beginRendering' in message) return 'beginRendering';
  if ('deleteSurface' in message) return 'deleteSurface';
  return 'unknown';
}
